/* Generated By:JJTree: Do not edit this line. ASTattr_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dotparser;

public
class ASTattr_stmt extends SimpleNode {
  public ASTattr_stmt(int id) {
    super(id);
  }

  public ASTattr_stmt(DOTParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DOTParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c94ee68fab5b58ab27074e597cfe7468 (do not edit this line) */
