/* Generated By:JJTree: Do not edit this line. ASTedgeRHS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dotparser;

public
class ASTedgeRHS extends SimpleNode {
  public ASTedgeRHS(int id) {
    super(id);
  }

  public ASTedgeRHS(DOTParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DOTParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=386159210c68470e06cc49c3af5d0260 (do not edit this line) */
